### PR TITLE
Pmemfile.v12.interpose

### PR DESCRIPTION
**Pull request by GBuella**
This change is [Reviewable](https://reviewable.io/reviews/marcinslusarz/nvml/10)

### CODE REVIEW

**Comment by marcinslusarz** [comment]
Review status: 0 of 57 files reviewed at latest revision, 9 unresolved discussions.

---

*[src/libpmemfile/Makefile, line 42 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/10#-KXB4I9LljdkDJvZgyLO:-KXB4I9LljdkDJvZgyLP:b-lsxluj) ([raw file](https://github.com/marcinslusarz/nvml/blob/21fc6662805a17a39d7efa6a523185390ef39292/src/libpmemfile/Makefile#L42)):*
> ```Makefile
> 
> ifeq ($(CAPSTONE_AVAILABLE),y)
> TARGETS += cintercept pmemfile_preload
> ```

just preload?

---

*[src/libpmemfile/cintercept/intercept.c, line 133 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/10#-KXB4pE3Pwx8Wp-xGx5c:-KXB4pE3Pwx8Wp-xGx5d:bauqta4) ([raw file](https://github.com/marcinslusarz/nvml/blob/21fc6662805a17a39d7efa6a523185390ef39292/src/libpmemfile/cintercept/intercept.c#L133)):*
> ```C
> 		"sed \"s/^/addr2line -p -f -e /\" > $tempfile ; "
> ```

two blank lines look odd here

---

*[src/libpmemfile/cintercept/intercept.c, line 171 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/10#-KXB51M_b9UmTqazyE9M:-KXB51M_b9UmTqazyE9N:bhh5tsq) ([raw file](https://github.com/marcinslusarz/nvml/blob/21fc6662805a17a39d7efa6a523185390ef39292/src/libpmemfile/cintercept/intercept.c#L171)):*
> ```C
> {
> 	/*
> 	 * Assume the library that provides pthread_create is libpthreads.
> ```

libpthread

---

*[src/libpmemfile/cintercept/intercept.c, line 173 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/10#-KXB53fsq5dPg2X5_FiH:-KXB53fsq5dPg2X5_FiI:b-7ropln) ([raw file](https://github.com/marcinslusarz/nvml/blob/21fc6662805a17a39d7efa6a523185390ef39292/src/libpmemfile/cintercept/intercept.c#L173)):*
> ```C
> 	 * Assume the library that provides pthread_create is libpthreads.
> 	 * Use dlsym instead of &pthread_create, as that would abort the
> 	 * program if libpthreads is not actually loaded.
> ```

ditto

---

*[src/libpmemfile/corelib/libpmemfile-core.map, line 107 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/10#-KXB42naSDUeBl2B45yn:-KXB42naSDUeBl2B45yo:b-a94x6k) ([raw file](https://github.com/marcinslusarz/nvml/blob/21fc6662805a17a39d7efa6a523185390ef39292/src/libpmemfile/corelib/libpmemfile-core.map#L107)):*
> ```
> 		pmemfile_fchmod;
> 		pmemfile_dup;
> 		pmemfile_dup2;
> ```

This list is duplicated.

---

*[src/libpmemfile/pmemfile_preload/Makefile, line 37 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/10#-KXB5yl_AMUTvkTtlhKo:-KXB5yl_AMUTvkTtlhKp:bg3z227) ([raw file](https://github.com/marcinslusarz/nvml/blob/21fc6662805a17a39d7efa6a523185390ef39292/src/libpmemfile/pmemfile_preload/Makefile#L37)):*
> ```Makefile
> 
> 
> LIBRARY_NAME = pmemfile_preload
> ```

Just pmemfile?

---

*[src/libpmemfile/pmemfile_preload/path_resolve.c, line 78 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/10#-KXB6AexXXeWMw6B9D_K:-KXB6AexXXeWMw6B9D_L:b3kre) ([raw file](https://github.com/marcinslusarz/nvml/blob/21fc6662805a17a39d7efa6a523185390ef39292/src/libpmemfile/pmemfile_preload/path_resolve.c#L78)):*
> ```C
> 	}
> 
> 	if (strcmp(path, "/dev/shm/dummy_mount_point/a") == 0) {
> ```

?

---

*[src/test/file_preload/a.expected_dump, line 0 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/10#-KXB6kn0WnRNeYhq6Jqd:-KXB6kn0WnRNeYhq6Jqe:b-7r90u1) ([raw file](https://github.com/marcinslusarz/nvml/blob/21fc6662805a17a39d7efa6a523185390ef39292/src/test/file_preload/a.expected_dump#L0)):*
This file is treated by both Github and Reviewable as binary. That's probably because of file extension. Please test whether this can be fixed.

---

*[src/test/file_preload/dummy_file_b, line 47 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/10#-KXB7ACSsEQX7pQ5rcAg:-KXB7ACSsEQX7pQ5rcAh:b5l56xl) ([raw file](https://github.com/marcinslusarz/nvml/blob/21fc6662805a17a39d7efa6a523185390ef39292/src/test/file_preload/dummy_file_b#L47)):*
> ```
> dummy_file dummy_file dummy_file dummy_file dummy_file dummy_file dummy_file
> 
> Látjátuk feleim szümtükhel, mik vogymuk: isa, por ës homou vogymuk. Mënyi milosztben terömtevé elevé miü isëmüköt Ádámot, ës adutta valá neki paradicsumot hazoá. Ës mënd paradicsumben valou gyimilcsëktul mondá neki élnië. Hëon tilutoá ut igy fá gyimilcsétul. Gye mondoá neki, mérët nüm ënëik : isa, ki napon ëmdöl az gyimilcstul, halálnek haláláal holsz. Hadlavá holtát terömtevé Istentul, gye feledevé. Engedé ürdüng intetüinek, ës ëvék az tilvot gyimilcstul. Ës az gyimilcsben halálut evék. Ës az gyimilcsnek úl keseröü valá vizë, hugy turkokat migé szakasztja valá. Nüm hëon mogánek, gye mënd u fajánek halálut ëvék. Haraguvék Isten, ës vetevé ut ez munkás világ belé: és lëün halálnek ës pukulnek fëszë, ës mënd u nemének. Kik azok? Miü vogymuk. Hugy ës tiü látjátuk szümtükhel: isa, ës nüm igy embër múlhatja ez vermöt, isa mënd azhuz járou vogymuk. Vimádjuk Uromk Isten këgyilmét ez lélekért, hugy jorgasson u neki, ës kegyigy-gyën, ës bulcsássa mënd u bunét!
> ```

This text was not written by Intel, so no Intel copyrights please.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/marcinslusarz/nvml/10)*

**Comment by GBuella** [comment]
Review status: 0 of 56 files reviewed at latest revision, 9 unresolved discussions.

---

*[src/libpmemfile/cintercept/intercept.c, line 133 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/10#-KXB4pE3Pwx8Wp-xGx5c:-KXBiZAm0_otCGV0ZNY_:b-896fix) ([raw file](https://github.com/marcinslusarz/nvml/blob/21fc6662805a17a39d7efa6a523185390ef39292/src/libpmemfile/cintercept/intercept.c#L133)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary>
> two blank lines look odd here
</details>
Done.

---

*[src/libpmemfile/cintercept/intercept.c, line 171 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/10#-KXB51M_b9UmTqazyE9M:-KXBiaRx7FE_niUAqaNz:b-896fix) ([raw file](https://github.com/marcinslusarz/nvml/blob/21fc6662805a17a39d7efa6a523185390ef39292/src/libpmemfile/cintercept/intercept.c#L171)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary>
> libpthread
</details>
Done.

---

*[src/libpmemfile/cintercept/intercept.c, line 173 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/10#-KXB53fsq5dPg2X5_FiH:-KXBibE3E-1OIJjqbpU2:b-896fix) ([raw file](https://github.com/marcinslusarz/nvml/blob/21fc6662805a17a39d7efa6a523185390ef39292/src/libpmemfile/cintercept/intercept.c#L173)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary>
> ditto
</details>
Done.

---

*[src/libpmemfile/pmemfile_preload/path_resolve.c, line 78 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/10#-KXB6AexXXeWMw6B9D_K:-KXBie0VjcSzDPP3E4L9:bg9rrh1) ([raw file](https://github.com/marcinslusarz/nvml/blob/21fc6662805a17a39d7efa6a523185390ef39292/src/libpmemfile/pmemfile_preload/path_resolve.c#L78)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary>
> ?
</details>
Dunno where that came from.
Done.

---

*[src/test/file_preload/dummy_file_b, line 47 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/10#-KXB7ACSsEQX7pQ5rcAg:-KXBinG5r1WbFkNtoPbP:b-896fix) ([raw file](https://github.com/marcinslusarz/nvml/blob/21fc6662805a17a39d7efa6a523185390ef39292/src/test/file_preload/dummy_file_b#L47)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary>
> This text was not written by Intel, so no Intel copyrights please.
</details>
Done.

---

*[src/libpmemfile/corelib/libpmemfile-core.map, line 107 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/10#-KXB42naSDUeBl2B45yn:-KXBipQX698u9KBmLCDA:b-896fix) ([raw file](https://github.com/marcinslusarz/nvml/blob/21fc6662805a17a39d7efa6a523185390ef39292/src/libpmemfile/corelib/libpmemfile-core.map#L107)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary>
> This list is duplicated.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/marcinslusarz/nvml/10)*

**Comment by marcinslusarz** [comment]
*[src/libpmemfile/cintercept/intercept.c, line 133 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/10#-KXB4pE3Pwx8Wp-xGx5c:-KXBjOeFAi9jymUxejeo:b-mgl1ll) ([raw file](https://github.com/marcinslusarz/nvml/blob/21fc6662805a17a39d7efa6a523185390ef39292/src/libpmemfile/cintercept/intercept.c#L133)):*
<details><summary><i>Previously, GBuella (Gábor Buella) wrote…</i></summary>
> Done.
</details>
They are still here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/marcinslusarz/nvml/10)*

**Comment by GBuella** [comment]
Review status: 0 of 56 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/libpmemfile/cintercept/intercept.c, line 133 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/10#-KXB4pE3Pwx8Wp-xGx5c:-KXBm-isXHs_FEyIntPr:b-sf3l26) ([raw file](https://github.com/marcinslusarz/nvml/blob/21fc6662805a17a39d7efa6a523185390ef39292/src/libpmemfile/cintercept/intercept.c#L133)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary>
> They are still here.
</details>
Done. I hope.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/marcinslusarz/nvml/10)*

**Pull request merged**
