### PR TITLE
file: refactor read/write

### PR DESCRIPTION
**Pull request by GBuella**
Remove global_offset.
Remove last_block_fill field from on media layout.

---
This change is [Reviewable](https://reviewable.io/reviews/marcinslusarz/nvml/53)

### CODE REVIEW

**Comment by marcinslusarz** [comment]
I'm happy with the code (barring very minor issues). I'll test its performance next week.

---

Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/libpmemfile-core/data.c, line 116 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/53#-KawlDqsQ7wzAzb7x_qw:-KawlDqtomyB0cqh3y7l:b-voqauo) ([raw file](https://github.com/marcinslusarz/nvml/blob/dcef7b9e8f3011d3917d92a3f8c65175a332173d/src/libpmemfile-core/data.c#L116)):*
> ```C
> 
> 	block = (void *)(uintptr_t)ctree_find_le_unlocked(file->vinode->blocks,
> 	    &off);
> ```

You can get rid of local variable and just use offset.

---

*[src/libpmemfile-core/data.c, line 144 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/53#-KawlRVVcB_iwD5vpdHS:-KawlRVWlT0iREcAH2v_:b-ij8yth) ([raw file](https://github.com/marcinslusarz/nvml/blob/dcef7b9e8f3011d3917d92a3f8c65175a332173d/src/libpmemfile-core/data.c#L144)):*
> ```C
> 		return file->block_pointer_cache;
> 
> 	uint64_t off = SSIZE_MAX;
> ```

why *signed* size max?

---

*[src/libpmemfile-core/data.c, line 274 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/53#-KawqO4tIzUEFw6N5DO1:-KawqO4tIzUEFw6N5DO2:bj0yapx) ([raw file](https://github.com/marcinslusarz/nvml/blob/dcef7b9e8f3011d3917d92a3f8c65175a332173d/src/libpmemfile-core/data.c#L274)):*
> ```C
> {
> 	if (inode->size >= new_size)
> 		return; /* No expansion needed */
> ```

please move this check to file_write

---

*[src/libpmemfile-core/data.c, line 296 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/53#-KawmdNTzCmG21dr4t_U:-KawmdNTzCmG21dr4t_V:bea3c0a) ([raw file](https://github.com/marcinslusarz/nvml/blob/dcef7b9e8f3011d3917d92a3f8c65175a332173d/src/libpmemfile-core/data.c#L296)):*
> ```C
> 			inode->size = new_size;
> 			return; /* No need to allocate new blocks */
> 		} else {
> ```

No "else {" please.

---

*[src/libpmemfile-core/data.c, line 317 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/53#-KawmtvxOUYWBGVkWiMh:-KawmtvxOUYWBGVkWiMi:b-9hom74) ([raw file](https://github.com/marcinslusarz/nvml/blob/dcef7b9e8f3011d3917d92a3f8c65175a332173d/src/libpmemfile-core/data.c#L317)):*
> ```C
> 	 * 64 kilobyte block size seems like a better option.
> 	 * todo: vehemently argue about the allocation strategy in the office,
> 	 * and hope for a consensus.
> ```

I honestly don't know what's the best strategy, so I'm not going to object to this idea. I planned to test something similar, but at the later phase.

---

*[src/libpmemfile-core/data.c, line 546 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/53#-KawrEQsNV91-vtwyQwx:-KawrEQsNV91-vtwyQwy:bj1wiqe) ([raw file](https://github.com/marcinslusarz/nvml/blob/dcef7b9e8f3011d3917d92a3f8c65175a332173d/src/libpmemfile-core/data.c#L546)):*
> ```C
> 		count = SIZE_MAX - file->offset;
> 
> 	/* XXX what is the maximum file size? Should it be SIZE_MAX? */
> ```

It should be something like this: SIZE_MAX - sizeof(obj metadata) - sizeof(root inode) - sizeof(inode). 
What's the problem? I think you handle it correctly. If user exceeds this value, he will get ENOSPC (the current error code is probably ENOMEM, but it doesn't matter now).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/marcinslusarz/nvml/53#-:-KawsbSoDE8P8WlB1m_g:bmy0uya)*

**Comment by GBuella** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/libpmemfile-core/data.c, line 116 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/53#-KawlDqsQ7wzAzb7x_qw:-Kb1KvY4UAZROYgS4NYJ:b-896fix) ([raw file](https://github.com/marcinslusarz/nvml/blob/dcef7b9e8f3011d3917d92a3f8c65175a332173d/src/libpmemfile-core/data.c#L116)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

You can get rid of local variable and just use offset.
</blockquote></details>

Done.

---

*[src/libpmemfile-core/data.c, line 144 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/53#-KawlRVVcB_iwD5vpdHS:-Kb1Kxg6-HaTh9udrWFu:bqc6td7) ([raw file](https://github.com/marcinslusarz/nvml/blob/dcef7b9e8f3011d3917d92a3f8c65175a332173d/src/libpmemfile-core/data.c#L144)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

why *signed* size max?
</blockquote></details>

Typo
Done.

---

*[src/libpmemfile-core/data.c, line 274 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/53#-KawqO4tIzUEFw6N5DO1:-Kb1L1EVaOCiGNBInoqh:b-896fix) ([raw file](https://github.com/marcinslusarz/nvml/blob/dcef7b9e8f3011d3917d92a3f8c65175a332173d/src/libpmemfile-core/data.c#L274)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

please move this check to file_write
</blockquote></details>

Done.

---

*[src/libpmemfile-core/data.c, line 296 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/53#-KawmdNTzCmG21dr4t_U:-Kb1L2AAAw5WAJIoPlfM:b-896fix) ([raw file](https://github.com/marcinslusarz/nvml/blob/dcef7b9e8f3011d3917d92a3f8c65175a332173d/src/libpmemfile-core/data.c#L296)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

No "else {" please.
</blockquote></details>

Done.

---

*[src/libpmemfile-core/data.c, line 546 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/53#-KawrEQsNV91-vtwyQwx:-Kb1L4PTIfKFfSh4XNLX:b-vpfsls) ([raw file](https://github.com/marcinslusarz/nvml/blob/dcef7b9e8f3011d3917d92a3f8c65175a332173d/src/libpmemfile-core/data.c#L546)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

It should be something like this: SIZE_MAX - sizeof(obj metadata) - sizeof(root inode) - sizeof(inode). 
What's the problem? I think you handle it correctly. If user exceeds this value, he will get ENOSPC (the current error code is probably ENOMEM, but it doesn't matter now).

</blockquote></details>

"What's the problem" - I don't know the max file size.
If the max file size is SIZE_MAX - sizeof(obj metadata) - sizeof(root inode), we should make it clear in the code somehow ( with a macro, or const size_t, or what not ).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/marcinslusarz/nvml/53)*

**Comment by GBuella** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/libpmemfile-core/data.c, line 317 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/53#-KawmtvxOUYWBGVkWiMh:-Kb1LoQzCeetPV99MMBx:b-3x29x7) ([raw file](https://github.com/marcinslusarz/nvml/blob/dcef7b9e8f3011d3917d92a3f8c65175a332173d/src/libpmemfile-core/data.c#L317)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

I honestly don't know what's the best strategy, so I'm not going to object to this idea. I planned to test something similar, but at the later phase.
</blockquote></details>

Reviewable says I should reply to it here so I do.
My reply is: I hate reviewable.io, please please stop making me use it.
Cheers

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/marcinslusarz/nvml/53)*

**Comment by marcinslusarz** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/libpmemfile-core/data.c, line 317 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/53#-KawmtvxOUYWBGVkWiMh:-Kb9mgikFKnKw7ikyUBF:b-6tfub4) ([raw file](https://github.com/marcinslusarz/nvml/blob/dcef7b9e8f3011d3917d92a3f8c65175a332173d/src/libpmemfile-core/data.c#L317)):*
<details><summary><i>Previously, GBuella (Gábor Buella) wrote…</i></summary><blockquote>

Reviewable says I should reply to it here so I do.
My reply is: I hate reviewable.io, please please stop making me use it.
Cheers
</blockquote></details>

It was my mistake. I should have set the comment to not requiring response.

---

*[src/libpmemfile-core/data.c, line 546 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/53#-KawrEQsNV91-vtwyQwx:-Kb9mo86nhJBHzf5XTKu:b-8rokgn) ([raw file](https://github.com/marcinslusarz/nvml/blob/dcef7b9e8f3011d3917d92a3f8c65175a332173d/src/libpmemfile-core/data.c#L546)):*
<details><summary><i>Previously, GBuella (Gábor Buella) wrote…</i></summary><blockquote>

"What's the problem" - I don't know the max file size.
If the max file size is SIZE_MAX - sizeof(obj metadata) - sizeof(root inode), we should make it clear in the code somehow ( with a macro, or const size_t, or what not ).
</blockquote></details>

To create files bigger than UINT64_MAX you need processor which can access more than 64 bits of address space and that much pmem. Currently it's not possible.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/marcinslusarz/nvml/53)*

**Comment by marcinslusarz** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/marcinslusarz/nvml/53)*

**Pull request merged**
