### PR TITLE
file: introduce sparse files

### PR DESCRIPTION
**Pull request by GBuella**
This change is [Reviewable](https://reviewable.io/reviews/marcinslusarz/nvml/58)

### CODE REVIEW

**Comment by marcinslusarz** [comment]
Review status: 0 of 7 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/libpmemfile-core/data.c, line 183 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/58#-KbuYc_HUp45qIZVkDgL:-KbuYc_HUp45qIZVkDgM:b2ibpt1) ([raw file](https://github.com/marcinslusarz/nvml/blob/a669ffb531436c4d937f1fdfdd0c34003c3471a9/src/libpmemfile-core/data.c#L183)):*
> ```C
> 			size = (uint32_t)count;
> 		else
> 			size = UINT32_MAX;
> ```

UINT32_MAX is not a multiple of FILE_PAGE_SIZE, so this will allocate unaligned block

---

*[src/libpmemfile-core/data.c, line 285 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/58#-KbuY-C5RWIrQGVQT6XB:-KbuY-C5RWIrQGVQT6XC:b-nufx8g) ([raw file](https://github.com/marcinslusarz/nvml/blob/a669ffb531436c4d937f1fdfdd0c34003c3471a9/src/libpmemfile-core/data.c#L285)):*
> ```C
> overallocate_size(uint64_t count)
> {
> 	/* XXX the original algorithm, just so tests pass */
> ```

Does this comment help in anything?

---

*[src/libpmemfile-core/data.c, line 304 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/58#-KbuXat-f7_hJ4J43WOi:-KbuXat0e3wGHoofQGDK:b-voqnn3) ([raw file](https://github.com/marcinslusarz/nvml/blob/a669ffb531436c4d937f1fdfdd0c34003c3471a9/src/libpmemfile-core/data.c#L304)):*
> ```C
> 
> 	/* make sure file size doesn't overflow while aligning the range size */
> 	ASSERT(offset + size < SIZE_MAX - 2 * FILE_PAGE_SIZE);
> ```

I'm not sure what are you trying to achieve here. If the comment is right, then previous assert handles it already.

---

*[src/libpmemfile-core/data.c, line 628 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/58#-KbuVAYzf2lNjSCtm-pV:-KbuVAYzf2lNjSCtm-pW:b-j0nwbg) ([raw file](https://github.com/marcinslusarz/nvml/blob/a669ffb531436c4d937f1fdfdd0c34003c3471a9/src/libpmemfile-core/data.c#L628)):*
> ```C
> 		new_size = file->offset + count;
> 
> 	/* All blocks needed for writing are properly allocated by this point */
> ```

s/by/at/ ?

---

*[src/libpmemfile-core/data.c, line 687 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/58#-KbuUqF4CfyOaHgNwd9y:-KbuUqF4CfyOaHgNwd9z:binj11v) ([raw file](https://github.com/marcinslusarz/nvml/blob/a669ffb531436c4d937f1fdfdd0c34003c3471a9/src/libpmemfile-core/data.c#L687)):*
> ```C
> 	} TX_ONABORT {
> 		vinode_destroy_data_state(vinode);
> 		error = errno;
> ```

swap those two lines - vinode_destroy_data_state may modify errno

---

*[src/libpmemfile-core/layout.h, line 61 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/58#-KbuTIV3NEvBX4Zx1R2v:-KbuTIV4ZH-6Ik2OWpHV:b1r4a1b) ([raw file](https://github.com/marcinslusarz/nvml/blob/a669ffb531436c4d937f1fdfdd0c34003c3471a9/src/libpmemfile-core/layout.h#L61)):*
> ```objc
> 
> enum block_flags {
> 	block_initialized = 1
> ```

please make this upper case

---

*[src/libpmemfile-core/layout.h, line 195 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/58#-KbuTE9k_OD0Y3yedFKu:-KbuTE9k_OD0Y3yedFKv:b-gja6yu) ([raw file](https://github.com/marcinslusarz/nvml/blob/a669ffb531436c4d937f1fdfdd0c34003c3471a9/src/libpmemfile-core/layout.h#L195)):*
> ```objc
>  *
>  * XXX: The current code can read from / write to blocks with any positive size,
>  * any offset alignment, so this information doessn't necessarily have to be
> ```

s/doessn't/doesn't/

---

*[src/libpmemfile-core/layout.h, line 197 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/58#-KbuTMtF5wjGh51jsXyV:-KbuTMtF5wjGh51jsXyW:b-lpr60z) ([raw file](https://github.com/marcinslusarz/nvml/blob/a669ffb531436c4d937f1fdfdd0c34003c3471a9/src/libpmemfile-core/layout.h#L197)):*
> ```objc
>  * any offset alignment, so this information doessn't necessarily have to be
>  * part of the on-media layout.
>  * But later the code might ( probably will ) depend on this.
> ```

s/( probably will )/(probably will)/

---

*[src/libpmemfile-core/pmemfile-core.c, line 79 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/58#-KbuUJ4amFHWSr2bGXqI:-KbuUJ4amFHWSr2bGXqJ:b6xxpf2) ([raw file](https://github.com/marcinslusarz/nvml/blob/a669ffb531436c4d937f1fdfdd0c34003c3471a9/src/libpmemfile-core/pmemfile-core.c#L79)):*
> ```C
> 			(pmemfile_core_block_size - 1) / FILE_PAGE_SIZE;
> 		pmemfile_core_block_size =
> 			(pmemfile_core_block_size + 1) * FILE_PAGE_SIZE;
> ```

just use roundup from sys/param.h

---

*[src/test/file_core_stat/out0.log.match, line 43 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/58#-KbubHl0v4WtLvkU8sDR:-KbubHl16P94ywNRyIjZ:b-8nfh19) ([raw file](https://github.com/marcinslusarz/nvml/blob/a669ffb531436c4d937f1fdfdd0c34003c3471a9/src/test/file_core_stat/out0.log.match#L43)):*
> ```
> st_size:    102400
> st_blksize: 1
> st_blocks:  224
> ```

That's suprising. Number of 512 byte blocks should stay the same.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/marcinslusarz/nvml/58)*

**Comment by GBuella** [comment]
Review status: 0 of 7 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/libpmemfile-core/data.c, line 183 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/58#-KbuYc_HUp45qIZVkDgL:-KbvP3uYL-GGTaIrB9cn:b-896fix) ([raw file](https://github.com/marcinslusarz/nvml/blob/a669ffb531436c4d937f1fdfdd0c34003c3471a9/src/libpmemfile-core/data.c#L183)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

UINT32_MAX is not a multiple of FILE_PAGE_SIZE, so this will allocate unaligned block
</blockquote></details>

Done.

---

*[src/libpmemfile-core/data.c, line 285 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/58#-KbuY-C5RWIrQGVQT6XB:-KbvP6PUaLhPNjYw0suX:b-8fgeyo) ([raw file](https://github.com/marcinslusarz/nvml/blob/a669ffb531436c4d937f1fdfdd0c34003c3471a9/src/libpmemfile-core/data.c#L285)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

Does this comment help in anything?
</blockquote></details>

Probably it doesn't help a lot.

---

*[src/libpmemfile-core/data.c, line 628 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/58#-KbuVAYzf2lNjSCtm-pV:-KbvPBbRZXwqx_Pd0tY3:b-896fix) ([raw file](https://github.com/marcinslusarz/nvml/blob/a669ffb531436c4d937f1fdfdd0c34003c3471a9/src/libpmemfile-core/data.c#L628)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

s/by/at/ ?
</blockquote></details>

Done.

---

*[src/libpmemfile-core/data.c, line 687 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/58#-KbuUqF4CfyOaHgNwd9y:-KbvPCQRFLr79P9Qq03u:b-896fix) ([raw file](https://github.com/marcinslusarz/nvml/blob/a669ffb531436c4d937f1fdfdd0c34003c3471a9/src/libpmemfile-core/data.c#L687)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

swap those two lines - vinode_destroy_data_state may modify errno
</blockquote></details>

Done.

---

*[src/libpmemfile-core/layout.h, line 61 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/58#-KbuTIV3NEvBX4Zx1R2v:-KbvPEDIUWZD-M2k92ft:b-896fix) ([raw file](https://github.com/marcinslusarz/nvml/blob/a669ffb531436c4d937f1fdfdd0c34003c3471a9/src/libpmemfile-core/layout.h#L61)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

please make this upper case
</blockquote></details>

Done.

---

*[src/libpmemfile-core/layout.h, line 195 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/58#-KbuTE9k_OD0Y3yedFKu:-KbvPEs0VIF1NP-XJjJO:b-896fix) ([raw file](https://github.com/marcinslusarz/nvml/blob/a669ffb531436c4d937f1fdfdd0c34003c3471a9/src/libpmemfile-core/layout.h#L195)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

s/doessn't/doesn't/
</blockquote></details>

Done.

---

*[src/libpmemfile-core/layout.h, line 197 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/58#-KbuTMtF5wjGh51jsXyV:-KbvPG1YElt6AXULuFO4:b-896fix) ([raw file](https://github.com/marcinslusarz/nvml/blob/a669ffb531436c4d937f1fdfdd0c34003c3471a9/src/libpmemfile-core/layout.h#L197)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

s/( probably will )/(probably will)/
</blockquote></details>

Done.

---

*[src/libpmemfile-core/pmemfile-core.c, line 79 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/58#-KbuUJ4amFHWSr2bGXqI:-KbvPII4Kzj73VZePGS8:b-92chj7) ([raw file](https://github.com/marcinslusarz/nvml/blob/a669ffb531436c4d937f1fdfdd0c34003c3471a9/src/libpmemfile-core/pmemfile-core.c#L79)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

just use roundup from sys/param.h
</blockquote></details>

Just made up my own roundup routine. Thank me for not using one more GNUism when porting to windows.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/marcinslusarz/nvml/58)*

**Comment by GBuella** [comment]
Review status: 0 of 7 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/libpmemfile-core/data.c, line 304 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/58#-KbuXat-f7_hJ4J43WOi:-KbvYakZ1W1FsdRy3W2W:bd7z8zs) ([raw file](https://github.com/marcinslusarz/nvml/blob/a669ffb531436c4d937f1fdfdd0c34003c3471a9/src/libpmemfile-core/data.c#L304)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

I'm not sure what are you trying to achieve here. If the comment is right, then previous assert handles it already.
</blockquote></details>

This piece of code quite wrong. I just remove it.

---

*[src/test/file_core_stat/out0.log.match, line 43 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/58#-KbubHl0v4WtLvkU8sDR:-KbvYkkuCVx81poJxPhy:b-d0ymue) ([raw file](https://github.com/marcinslusarz/nvml/blob/a669ffb531436c4d937f1fdfdd0c34003c3471a9/src/test/file_core_stat/out0.log.match#L43)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

That's suprising. Number of 512 byte blocks should stay the same.
</blockquote></details>

Surprise explained in person.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/marcinslusarz/nvml/58)*

**Comment by GBuella** [comment]
Review status: 0 of 7 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/libpmemfile-core/data.c, line 304 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/58#-KbuXat-f7_hJ4J43WOi:-KbvZJBHaKjDXIYPZoFQ:b9o3dy9) ([raw file](https://github.com/marcinslusarz/nvml/blob/a669ffb531436c4d937f1fdfdd0c34003c3471a9/src/libpmemfile-core/data.c#L304)):*
> code quite wrong
*code is quite wrong*

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/marcinslusarz/nvml/58)*

**Comment by marcinslusarz** [comment]
Review status: 0 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/libpmemfile-core/data.c, line 285 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/58#-KbuY-C5RWIrQGVQT6XB:-KbydHAqtMNa45ZyijrP:b-942h1k) ([raw file](https://github.com/marcinslusarz/nvml/blob/a669ffb531436c4d937f1fdfdd0c34003c3471a9/src/libpmemfile-core/data.c#L285)):*
<details><summary><i>Previously, GBuella (Gábor Buella) wrote…</i></summary><blockquote>

Probably it doesn't help a lot.
</blockquote></details>

So what's the point of it? Can you remove it?

XXX is supposed to mark things to fix, but I don't see what can be fixed here.

---

*[src/libpmemfile-core/data.c, line 175 at r2](https://reviewable.io:443/reviews/marcinslusarz/nvml/58#-Kbyd6RmQN0Ak6ldPNev:-Kbyd6RmQN0Ak6ldPNew:b-kt0kej) ([raw file](https://github.com/marcinslusarz/nvml/blob/d764a3d4bdadf881ca0d23e4db0174112e9e9b6c/src/libpmemfile-core/data.c#L175)):*
> ```C
> 
> 	if (pmemfile_core_block_size != 0) {
> 		ASSERT(pmemfile_core_block_size > 0);
> ```

pmemfile_core_block_size is unsigned and you just checked it's not zero one line above

---

*[src/libpmemfile-core/data.c, line 296 at r2](https://reviewable.io:443/reviews/marcinslusarz/nvml/58#-Kbyn85w0jjuKRiwxBBi:-Kbyn85w0jjuKRiwxBBj:b-mvohu8) ([raw file](https://github.com/marcinslusarz/nvml/blob/d764a3d4bdadf881ca0d23e4db0174112e9e9b6c/src/libpmemfile-core/data.c#L296)):*
> ```C
> 		return 64 * 1024 * 1024;
> 	else
> 		return count;
> ```

Hmm. Before this change maximum block size was 64MB. After this patch it can be any size. I think limiting block sizes can be beneficial e.g. for supporting truncate, especially when file system is close to being full.

---

*[src/libpmemfile-core/pmemfile-core.c, line 79 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/58#-KbuUJ4amFHWSr2bGXqI:-Kbyopo3iTnM0aW_9AS1:b-tyxu08) ([raw file](https://github.com/marcinslusarz/nvml/blob/a669ffb531436c4d937f1fdfdd0c34003c3471a9/src/libpmemfile-core/pmemfile-core.c#L79)):*
<details><summary><i>Previously, GBuella (Gábor Buella) wrote…</i></summary><blockquote>

Just made up my own roundup routine. Thank me for not using one more GNUism when porting to windows.
</blockquote></details>

Can you at least the same algorithm as in sys/param.h? I think it's simpler/more idiomatic.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/marcinslusarz/nvml/58)*

**Comment by marcinslusarz** [comment]
Review status: 0 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/libpmemfile-core/data.c, line 199 at r2](https://reviewable.io:443/reviews/marcinslusarz/nvml/58#-KbypUbVHLWIRk7bY_o_:-KbypUbWpvxXRIF3wAMy:b59f15r) ([raw file](https://github.com/marcinslusarz/nvml/blob/d764a3d4bdadf881ca0d23e4db0174112e9e9b6c/src/libpmemfile-core/data.c#L199)):*
> ```C
> 			size = UINT32_MAX;
> 		else
> 			size = (uint32_t)(usable & ~(FILE_PAGE_SIZE - 1));
> ```

I think rounddown should be done for both code paths.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/marcinslusarz/nvml/58)*

**Comment by marcinslusarz** [comment]
Review status: 0 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/libpmemfile-core/pmemfile-core.c, line 79 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/58#-KbuUJ4amFHWSr2bGXqI:-Kbyq6LTyM06iKl6gzT4:buxilxm) ([raw file](https://github.com/marcinslusarz/nvml/blob/a669ffb531436c4d937f1fdfdd0c34003c3471a9/src/libpmemfile-core/pmemfile-core.c#L79)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

Can you at least the same algorithm as in sys/param.h? I think it's simpler/more idiomatic.
</blockquote></details>

use the same algo*

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/marcinslusarz/nvml/58)*

**Comment by GBuella** [comment]
Review status: 0 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/libpmemfile-core/data.c, line 285 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/58#-KbuY-C5RWIrQGVQT6XB:-Kbys1CiIGoElqtzly6F:b7eqyyv) ([raw file](https://github.com/marcinslusarz/nvml/blob/a669ffb531436c4d937f1fdfdd0c34003c3471a9/src/libpmemfile-core/data.c#L285)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

So what's the point of it? Can you remove it?

XXX is supposed to mark things to fix, but I don't see what can be fixed here.
</blockquote></details>

To fix: find better algo. Anyways, I remove this comment.

---

*[src/libpmemfile-core/data.c, line 175 at r2](https://reviewable.io:443/reviews/marcinslusarz/nvml/58#-Kbyd6RmQN0Ak6ldPNev:-KbyrbcwgPa6CvCIf6Xb:b-896fix) ([raw file](https://github.com/marcinslusarz/nvml/blob/d764a3d4bdadf881ca0d23e4db0174112e9e9b6c/src/libpmemfile-core/data.c#L175)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

pmemfile_core_block_size is unsigned and you just checked it's not zero one line above
</blockquote></details>

Done.

---

*[src/libpmemfile-core/data.c, line 199 at r2](https://reviewable.io:443/reviews/marcinslusarz/nvml/58#-KbypUbVHLWIRk7bY_o_:-KbyrqauI9QfUnrDWZle:b-gojhqq) ([raw file](https://github.com/marcinslusarz/nvml/blob/d764a3d4bdadf881ca0d23e4db0174112e9e9b6c/src/libpmemfile-core/data.c#L199)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

I think rounddown should be done for both code paths.
</blockquote></details>

I just replaced UINT32_MAX with  MAX_BLOCK_SIZE, it was a typo really

---

*[src/libpmemfile-core/data.c, line 296 at r2](https://reviewable.io:443/reviews/marcinslusarz/nvml/58#-Kbyn85w0jjuKRiwxBBi:-KbysBNVweG2d1SmoGpB:b-o1ivva) ([raw file](https://github.com/marcinslusarz/nvml/blob/d764a3d4bdadf881ca0d23e4db0174112e9e9b6c/src/libpmemfile-core/data.c#L296)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

Hmm. Before this change maximum block size was 64MB. After this patch it can be any size. I think limiting block sizes can be beneficial e.g. for supporting truncate, especially when file system is close to being full.
</blockquote></details>

This is not the block size, this is the range size.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/marcinslusarz/nvml/58)*

**Comment by GBuella** [comment]
Review status: 0 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/libpmemfile-core/pmemfile-core.c, line 79 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/58#-KbuUJ4amFHWSr2bGXqI:-KbyuNAR4XalGa0grZRn:b-896fix) ([raw file](https://github.com/marcinslusarz/nvml/blob/a669ffb531436c4d937f1fdfdd0c34003c3471a9/src/libpmemfile-core/pmemfile-core.c#L79)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

use the same algo*
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/marcinslusarz/nvml/58)*

**Comment by marcinslusarz** [comment]
Reviewed 4 of 7 files at r1, 1 of 3 files at r2.
Review status: 5 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/libpmemfile-core/data.c, line 357 at r2](https://reviewable.io:443/reviews/marcinslusarz/nvml/58#-KbywFHJza_-HUgLe-mb:-KbywFHJza_-HUgLe-mc:bqk0g69) ([raw file](https://github.com/marcinslusarz/nvml/blob/d764a3d4bdadf881ca0d23e4db0174112e9e9b6c/src/libpmemfile-core/data.c#L357)):*
> ```C
> 
> 			uint64_t next_offset =
> 			    file->vinode->first_block->offset;
> ```

If you move this variable to the beginning of this code block you will be able to use it in 1st if

---

*[src/libpmemfile-core/data.c, line 478 at r2](https://reviewable.io:443/reviews/marcinslusarz/nvml/58#-KbyyNMacLrK3HNu-lwL:-KbyyNMbRLLWUEs5MWLk:b-d7mtgd) ([raw file](https://github.com/marcinslusarz/nvml/blob/d764a3d4bdadf881ca0d23e4db0174112e9e9b6c/src/libpmemfile-core/data.c#L478)):*
> ```C
> 			VALGRIND_ADD_TO_TX(start_zero, count);
> 			pmemobj_memset_persist(pfp->pop, start_zero, 0, count);
> 			VALGRIND_REMOVE_FROM_TX(start_zero, count);
> ```

As an optimization we can surround both memsets (+valgrind macros) with "if (count)"

---

*[src/libpmemfile-core/data.c, line 555 at r2](https://reviewable.io:443/reviews/marcinslusarz/nvml/58#-Kbyznin-haeN986Z9Gv:-Kbyznin-haeN986Z9Gw:b-n2lz3x) ([raw file](https://github.com/marcinslusarz/nvml/blob/d764a3d4bdadf881ca0d23e4db0174112e9e9b6c/src/libpmemfile-core/data.c#L555)):*
> ```C
> 		/*
> 		 * Two more asserts, that should stay here as long as
> 		 * sparse files are not implemented.
> ```

Don't we need to do something about this comment? :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/marcinslusarz/nvml/58)*

**Comment by GBuella** [comment]
Review status: 5 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/libpmemfile-core/data.c, line 357 at r2](https://reviewable.io:443/reviews/marcinslusarz/nvml/58#-KbywFHJza_-HUgLe-mb:-Kbz0rapiPhVwI2QaPv9:bo8bupm) ([raw file](https://github.com/marcinslusarz/nvml/blob/d764a3d4bdadf881ca0d23e4db0174112e9e9b6c/src/libpmemfile-core/data.c#L357)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

If you move this variable to the beginning of this code block you will be able to use it in 1st if
</blockquote></details>

Infact, I just realized it is wrong. This should be check correctly before calling allocate_block.

---

*[src/libpmemfile-core/data.c, line 478 at r2](https://reviewable.io:443/reviews/marcinslusarz/nvml/58#-KbyyNMacLrK3HNu-lwL:-Kbz1DlFXJ8IM1w7ars0:bwqufgu) ([raw file](https://github.com/marcinslusarz/nvml/blob/d764a3d4bdadf881ca0d23e4db0174112e9e9b6c/src/libpmemfile-core/data.c#L478)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

As an optimization we can surround both memsets (+valgrind macros) with "if (count)"
</blockquote></details>

Actually, probably pmemobj_memset_persist takes care of that. And VALGRIND_ADD_TO_TX is not compiled in the final optimized release anyways.

---

*[src/libpmemfile-core/data.c, line 555 at r2](https://reviewable.io:443/reviews/marcinslusarz/nvml/58#-Kbyznin-haeN986Z9Gv:-Kbz1s-UmLV2Dr19tfFB:ba3dfob) ([raw file](https://github.com/marcinslusarz/nvml/blob/d764a3d4bdadf881ca0d23e4db0174112e9e9b6c/src/libpmemfile-core/data.c#L555)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

Don't we need to do something about this comment? :)
</blockquote></details>

Removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/marcinslusarz/nvml/58)*

**Comment by GBuella** [comment]
Review status: 5 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/libpmemfile-core/data.c, line 555 at r2](https://reviewable.io:443/reviews/marcinslusarz/nvml/58#-Kbyznin-haeN986Z9Gv:-Kbz2Q8JGGnU0ppIlB75:b-896fix) ([raw file](https://github.com/marcinslusarz/nvml/blob/d764a3d4bdadf881ca0d23e4db0174112e9e9b6c/src/libpmemfile-core/data.c#L555)):*
<details><summary><i>Previously, GBuella (Gábor Buella) wrote…</i></summary><blockquote>

Removed
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/marcinslusarz/nvml/58)*

**Comment by marcinslusarz** [comment]
*[src/libpmemfile-core/data.c, line 478 at r2](https://reviewable.io:443/reviews/marcinslusarz/nvml/58#-KbyyNMacLrK3HNu-lwL:-KbzBRwXJA35BOf8R40-:bi2s9s6) ([raw file](https://github.com/marcinslusarz/nvml/blob/d764a3d4bdadf881ca0d23e4db0174112e9e9b6c/src/libpmemfile-core/data.c#L478)):*
<details><summary><i>Previously, GBuella (Gábor Buella) wrote…</i></summary><blockquote>

Actually, probably pmemobj_memset_persist takes care of that. And VALGRIND_ADD_TO_TX is not compiled in the final optimized release anyways.
</blockquote></details>

But there are 4 or 5 function pointers before checking that... And Valgrind macros are quite verbose (if you look at the assembly), so I'd prefer to skip them when possible.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/marcinslusarz/nvml/58)*

**Comment by GBuella** [comment]
Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/libpmemfile-core/data.c, line 478 at r2](https://reviewable.io:443/reviews/marcinslusarz/nvml/58#-KbyyNMacLrK3HNu-lwL:-KbzD8SEI6JVYCU-NGKM:b-896fix) ([raw file](https://github.com/marcinslusarz/nvml/blob/d764a3d4bdadf881ca0d23e4db0174112e9e9b6c/src/libpmemfile-core/data.c#L478)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

But there are 4 or 5 function pointers before checking that... And Valgrind macros are quite verbose (if you look at the assembly), so I'd prefer to skip them when possible.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/marcinslusarz/nvml/58)*

**Comment by marcinslusarz** [comment]
Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/marcinslusarz/nvml/58)*

**Pull request merged**
