### PR TITLE
file: ignore file access rights in log matching

### PR DESCRIPTION
**Pull request by GBuella**
This change is [Reviewable](https://reviewable.io/reviews/marcinslusarz/nvml/55)

### CODE REVIEW

**Comment by marcinslusarz** [comment]
Why? Shouldn't we fix the underlying problem?

**Comment by GBuella** [comment]
We use e.g. the cp command found on a particular platform during these tests, which makes things not very predictable. Probably, eventually these tests should be replaced with some more deterministic tests, but for now I consider this a fix.

**Comment by marcinslusarz** [comment]
So the problem is with source files created outside of pmemfile? Can't we just chmod them before copying?

**Comment by GBuella** [comment]
What the file is owned by someone else? ( 'git clone' as user X, 'make' as user Y )
What is it still takes into account umask, and umask is set something unexpected?
What if try to chmod after copying, and the particular chmod implementation uses some syscall that we don't understand yet?
What if...anything? The details of these executables ( cp, chmod ) are out of our control.

**Comment by marcinslusarz** [comment]
1) Already not supported by nvml.
2) That's why I would like to understand where's the problem. If something fails in unusual configuration it's better to know about it and handle it.
3) I proposed to chmod before, not after. If cp does something weird on a target file, it's better to know about it.
4) Part of the implementation of pmemfile is finding those corner cases. If we'll discover there's too much variability in behavior of standard tools, we can workaround them in a way you propose.

Maybe instead of chmod on those files, we should set umask to some specific value?

**Comment by GBuella** [comment]
OK, I'll add chmod, and see how that works out.

**Pull request closed without merging**
